<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <UseWPF>false</UseWPF>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>
</Project>